[options.entry_points]
console_scripts =
    demo_show = crazyflie_shows.demo_show:main
    swarm_show = crazyflie_shows.swarm_show:main
    plan_show = crazyflie_shows.plan_show:main
    constellation_show = crazyflie_shows.constellation_show:main
    escort_show = crazyflie_shows.escort_show:main
    escort_teleop = crazyflie_shows.escort_teleop:main
    plan_escort = crazyflie_shows.plan_escort:main
    plan_constellation = crazyflie_shows.plan_show:main_constellation
